#!/bin/sh
mount -t proc proc /proc
mount -t tmpfs tmpfs /tmp
mount -t sysfs sysfs /sysfs

mknod /dev/hda b 3 0
mknod /dev/hda1 b 3 1
mknod /dev/hda2 b 3 2
mknod /dev/hda3 b 3 3
mknod /dev/hda4 b 3 4

mknod /dev/mem c 1 1
mknod /dev/kmem c 1 2
mknod /dev/null c 1 3
mknod /dev/port c 1 4
mknod /dev/zero c 1 5
mknod /dev/full c 1 7
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/kmsg c 1 11

ifconfig lo 127.0.0.1 up

/usr/local/bin/fsimage_guest

poweroff
